export const STICKER_COPY = {
  title: '貼紙學單字',
  subtitle: '拖貼紙配英文詞，全部放對就過關',
  mission: '拖貼紙配英文詞',
  guideMain: '把貼紙拖到對應的英文詞。',
  guideSub: '放對會貼上並讀出英文；放錯沒有鎖，可以再拖。',
  wrong: '再試一次，慢慢配。',
  blocked: '呢格已經有貼紙，試另一格啦。',
  welcomeEyebrow: '圖 對 英 文 詞',
  welcomeBody: '拖貼紙配英文詞，全部放對就過關。過關之後可以玩下一關。',
  start: '開始遊戲',
  winEyebrow: '任 務 完 成',
  winTitle: '全部放對了！',
  winBody: '圖都配好英文詞喇。可以玩下一關，會再抽一組圖詞。',
  next: '下一關',
  replay: '再玩本關',
  home: '回 Hub',
  helpTitle: '遊戲說明',
  task: '圖詞配對練習。把貼紙拖到對應的英文詞，全部放對就過關。',
  controls: '從托盤拖貼紙到英文詞格子。放對會貼上並讀出英文；放錯沒有鎖、沒有扣分，可以再拖。放對後仍可拖出來重放。',
  parent: '目標：圖詞配對練習。提問：呢張圖係咩？邊個英文詞？示範：家長拖一張放對後交返孩子。',
  trayLabel: '貼紙托盤',
  slotsLabel: '英文詞格子',
  footer: ['從容遊玩', '不計時 · 不扣分', '圖詞配對'] as const,
} as const;
